/*Copyright (c) 2019-2020 imaginea.com All Rights Reserved.
 This software is the confidential and proprietary information of imaginea.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with imaginea.com*/
package com.testing_pdf.myjavaservice.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import javax.servlet.http.HttpServletRequest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.testing_pdf.myjavaservice.MyJavaService;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;

/**
 * Controller object for domain model class {@link MyJavaService}.
 * @see MyJavaService
 */
@RestController
@Api(value = "MyJavaController", description = "controller class for java service execution")
@RequestMapping("/myJava")
public class MyJavaController {

    @Autowired
    private MyJavaService myJavaService;

    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @RequestMapping(value = "/convert", method = RequestMethod.GET)
    public String convert(@RequestParam(value = "urlpath_fromxml", required = false) String urlpath_fromxml, @RequestParam(value = "urlpath_fromxml1", required = false) String urlpath_fromxml1, @RequestParam(value = "urlpath_fromxml3", required = false) String urlpath_fromxml3, @RequestParam(value = "urlpath_fromxml4", required = false) String urlpath_fromxml4, @RequestParam(value = "urlpath_fromxml5", required = false) String urlpath_fromxml5, @RequestParam(value = "urlpath_fromxml6", required = false) String urlpath_fromxml6, @RequestParam(value = "urlpath_fromxml7", required = false) String urlpath_fromxml7, @RequestParam(value = "urlpath_fromxml8", required = false) String urlpath_fromxml8, @RequestParam(value = "urlpath_fromxml9", required = false) String urlpath_fromxml9, @RequestParam(value = "urlpath_fromxml10", required = false) String urlpath_fromxml10) throws Exception {
        return myJavaService.convert(urlpath_fromxml, urlpath_fromxml1, urlpath_fromxml3, urlpath_fromxml4, urlpath_fromxml5, urlpath_fromxml6, urlpath_fromxml7, urlpath_fromxml8, urlpath_fromxml9, urlpath_fromxml10);
    }

    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @RequestMapping(value = "/sampleJavaOperation", method = RequestMethod.GET)
    public String sampleJavaOperation(@RequestParam(value = "name", required = false) String name,  HttpServletRequest request) {
        return myJavaService.sampleJavaOperation(name, request);
    }
}